# config/short_term_config.yaml

# Configuration for short-term data collection (updated every minute)
electrode_1:
  connection_string: "DRIVER={AspenTech SQLplus};HOST=MFCSMES;PORT=10014;ADS=MFCSIP21;READONLY=N;Trusted_Connection=yes;"
  period: 00:01:00
  time_window: 24:00:00
  tag_names:
    M1 Furnace Power(MW): M1-FCE-MTR-FRN-Pwr-Tot
    M1 Furnace Power(SP): M1_MINSTRAL_MW_SP
    M1 Furnace Tap Changers in Auto: M1-SEL-GRP-AUTOUTIL
    Electrode 1 in Auto: M1-ELE-260101-UTIl
    Electrode Control Active: M1_ELE_260101_AUTOACT
    Electrode 1 I2: M1-FCE-UI-399-Total
    Electrode 1 Raise Lock: M1_MINSTRAL_EL_INHIT_UP1
    Electrode 1 lower Lock: M1_MINSTRAL_EL_INHIT_DN1
    Electrode 1 Stk Up: M1_MINSTRAL_EL_STK_UP_1
    Electrode 1 Stk Dn: M1_MINSTRAL_EL_STK_DN_1
    Electrode 1 Paste Temperature: M1-EEA-TI-105
    Electrode 1 Power: M1_MINSTRAL_EL_MW_1
    Electrode 1 Current(kA): M1_MINSTRAL_EL_CUR_1
    Electrode 1 Resistance Target: M1_MINSTRAL_EL_R_SP_1
    Electrode Resistance(mOhm): M1_MINSTRAL_EL_R_1
    Electrode 1 Position(mm): M1_MINSTRAL_EL_POS_1
    Electrode 1 Tenor(mm/min): M1-ELE-260101-TEN
    Electrode 1 Wesly: M1-EEA-WESTCONST-E1-PV
    Electrode 1 Slip: M1-ELS-260101-LST-SLP
    TX12 Tap Changer Position: M1-SEL-260182-TAPPOS
    TX23 Tap Cahnger Position: M1-SEL-260183-TAPPOS
    TX31 Tap Changer Position: M1-SEL-260184-TAPPOS
    M1 Tapping: M1-TapHole
    M1 Tap Acummulator: M1-FCE-UI-395

  reference_limits:
    Electrode 1 Current(kA):
      min: 84.6
      sp: 92.3
      max: 100.0
    Electrode Resistance(mOhm):
      min: 1.5
      max: 2.5
    Electrode 1 Position(mm):
      min: 200
      max: 450
    Electrode 1 Tenor(mm/min):
      min: 300
      max: 1200
    Electrode 1 Wesly:
      min: 13.5
      sp: 14.5
      max: 15.5
